// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dXAJc
RcppExport SEXP dXAJc(SEXP modelParameter1, SEXP basinInfo1, SEXP basinData1);
RcppExport SEXP _RXAJ_dXAJc(SEXP modelParameter1SEXP, SEXP basinInfo1SEXP, SEXP basinData1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type modelParameter1(modelParameter1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type basinInfo1(basinInfo1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type basinData1(basinData1SEXP);
    rcpp_result_gen = Rcpp::wrap(dXAJc(modelParameter1, basinInfo1, basinData1));
    return rcpp_result_gen;
END_RCPP
}
// hXAJc
RcppExport SEXP hXAJc(SEXP modelParameter1, SEXP basinInfo1, SEXP basinData1);
RcppExport SEXP _RXAJ_hXAJc(SEXP modelParameter1SEXP, SEXP basinInfo1SEXP, SEXP basinData1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type modelParameter1(modelParameter1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type basinInfo1(basinInfo1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type basinData1(basinData1SEXP);
    rcpp_result_gen = Rcpp::wrap(hXAJc(modelParameter1, basinInfo1, basinData1));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP dXAJc(SEXP, SEXP, SEXP);
RcppExport SEXP hXAJc(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_RXAJ_dXAJc", (DL_FUNC) &_RXAJ_dXAJc, 3},
    {"_RXAJ_hXAJc", (DL_FUNC) &_RXAJ_hXAJc, 3},
    {"dXAJc",       (DL_FUNC) &dXAJc,       3},
    {"hXAJc",       (DL_FUNC) &hXAJc,       3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RXAJ(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
