# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dXAJc <- function(modelParameter1, basinInfo1, basinData1) {
    .Call(`_RXAJ_dXAJc`, modelParameter1, basinInfo1, basinData1)
}

hXAJc <- function(modelParameter1, basinInfo1, basinData1) {
    .Call(`_RXAJ_hXAJc`, modelParameter1, basinInfo1, basinData1)
}

